manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

  self:
    path: .
    # 新增这一行！告诉west去仓库根目录找boards文件夹
    local-board-paths: ["../boards"]
