manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
    # 如果要使用extra‑modules，必须放在self下面，不能写在manifest顶层
    # extra-modules:
    #   - your‑module‑name
