CONFIG_SOC_SERIES_NRF52840=y
CONFIG_BOARD_NRF52840_NORDIC_NRF52840DK_NRF52840=y

CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_KEYBOARD_ROLE=y
CONFIG_ZMK_KSCAN=y
CONFIG_ZMK_SLEEP=y
CONFIG_CONSOLE=n
CONFIG_SERIAL=n
